language: python
sudo: false

python:
  - "2.7"

jdk:
  - oraclejdk8

env:
  - TOXENV=flake8
  - TOXENV=docs
  - TOXENV=assets
  - TOXENV=es
  - TOXENV=addons
  - TOXENV=devhub
  - TOXENV=editors
  - TOXENV=amo
  - TOXENV=users
  - TOXENV=main

matrix:
  fast_finish: true

cache:
  pip: true
  directories:
    - node_modules
    - .tox

services:
  - memcached

addons:
  apt:
    packages:
      - swig

before_install:
  - scripts/travis_es.sh
  - /tmp/elasticsearch/elasticsearch-5.1.1/bin/elasticsearch -d -E path.data=/tmp -E index.store.type=mmapfs -v

install:
  - nvm current
  - nvm deactivate
  - nvm install 4
  - nvm use 4
  - pip install --upgrade pip wheel setuptools coverage codecov tox==1.8.1

before_script:
  - mysql -e 'create database olympia;'
  - node --version
  - /tmp/elasticsearch/elasticsearch-5.1.1/bin/elasticsearch --version
  - sleep 10

script:
  - coverage erase
  - RUNNING_IN_CI=True tox -v
  - coverage combine

notifications:
  irc:
    channels:
      - "irc.mozilla.org#amo-bots"
    on_success: change
    on_failure: always
  webhooks:
    # trigger Buildtime Trend Service to parse Travis CI log
    - https://buildtimetrend.herokuapp.com/travis

after_success:
  - coverage report
  - codecov

git:
  depth: 3
